name: udmse-podman

on:
  push:
    branches: 
      - master


env:
  BUILD_VERSION: ${{ github.ref_name }}
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit

      - name: Source checkout
        uses: actions/checkout@v3
 
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=sha,format=long,prefix=sha256:
          labels: |
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}

      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: push-step
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          platforms: linux/arm64
          build-args: |
            RELEASE=${{ env.BUILD_VERSION }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
      - name: Extract
        run: |
          docker cp $(docker create ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}):/build/udmse-podman-${{ env.BUILD_VERSION }}.tar.gz udmse-podman-${{ env.BUILD_VERSION }}.tar.gz

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: udmse-podman-${{ env.BUILD_VERSION }}.tar.gz
          name: udmse-podman-${{ env.BUILD_VERSION }}.tar.gz

